# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KiteFlyer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KiteFlyer
  pod 'Alamofire', '~> 4.4'
  pod 'Zip', '~> 0.6'
  
end
